# Generated by Django 4.2.4 on 2023-09-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='confromPassword',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
